maxTotalConcurrency: 100
maxTxConcurrency: 20
defaultSecretKey: "secret-key"
defaultDatabase: "crm-system"
defaultRequestTimeoutSec: 30

clusterNodes:
  - baseUrl: "http://localhost:5678"
    secretKey: "secret-key"
  - baseUrl: "http://localhost:5678"
