defaultSecretKey: "secret-key"
defaultDatabase: "crm-system"
maxConcurrency: 100

clusterNodes:
  - baseUrl: "http://localhost:5678"
    secretKey: "secret-key"
  - baseUrl: "http://localhost:5678"
  - baseUrl: "http://localhost:5678"
  - baseUrl: "http://localhost:5678"
