nodeName: "dbapi-1"
nodePort: 5678
maxHttpSessions: 1000
secretKey: "change-me"

clusterNodes:
  - "http://localhost:5678"
  - "http://localhost:5679"
  - "http://localhost:5680"

datasources:
  - datasourceId: pg_master
    databaseName: crm-system
    driver: postgres
    dsn: "postgres://user:password@localhost:25432/incident_manager"
    maxOpenConns: 100
    minIdleConns: 10
    maxConnLifetimeSec: 1800
    maxTxConns: 5
    maxTxIdleTimeoutSec: 15
    defaultQueryTimeoutSec: 30
    readonly: false
  - datasourceId: pg_slave01
    databaseName: crm-system
    driver: postgres
    dsn: "postgres://user:password@localhost:25432/incident_manager"
    maxOpenConns: 100
    minIdleConns: 10
    maxConnLifetimeSec: 1800
    maxTxConns: 5
    maxTxIdleTimeoutSec: 15
    defaultQueryTimeoutSec: 30
    readonly: true
