nodeId: "dbapi-1"
nodePort: 5678
maxHttpSessions: 1000
secretKey: "change-me"

datasources:
  - datasourceId: pg_master
    databaseName: crm-system
    driver: postgres
    dsn: "postgres://user:password@localhost:25432/incident_manager"
    maxOpenConns: 100
    minIdleConns: 10
    maxTransactionConns: 5
    connMaxLifetimeSec: 1800
    defaultTxTimeoutSec: 300
    defaultQueryTimeoutSec: 30
    readonly: false
  - datasourceId: pg_slave01
    databaseName: crm-system
    driver: postgres
    dsn: "postgres://user:password@localhost:25432/incident_manager"
    maxOpenConns: 50
    minIdleConns: 5
    maxTransactionConns: 0
    connMaxLifetimeSec: 1800
    defaultTxTimeoutSec: 300
    defaultQueryTimeoutSec: 30
    readonly: true

cluster:
  - nodeId: "dbapi-1"
    baseUrl: "http://localhost:5678"
  - nodeId: "dbapi-2"
    baseUrl: "http://localhost:5678"
  - nodeId: "dbapi-3"
    baseUrl: "http://localhost:5678"
