nodeName: "dbapi-1"
nodePort: 5678
maxHttpQueue: 1000
secretKey: "secret-key"

clusterNodes:
  - "http://localhost:5678"
  - "http://localhost:5678"
  - "http://localhost:5678"
  - "http://localhost:5678"


myDatasources:
  - datasourceId: pg_master
    databaseName: crm-system
    driver: postgres
    dsn: "postgres://admin:abcd1234@localhost:5432/lps"
    maxOpenConns: 100
    maxIdleConns: 10
    maxConnLifetimeSec: 1800
    maxTxConns: 5
    maxTxIdleTimeoutSec: 15
    defaultQueryTimeoutSec: 30
    readonly: false
  - datasourceId: pg_slave01
    databaseName: crm-system
    driver: postgres
    dsn: "postgres://admin:abcd1234@localhost:5432/lps"
    maxOpenConns: 100
    maxIdleConns: 10
    maxConnLifetimeSec: 1800
    maxTxConns: 5
    maxTxIdleTimeoutSec: 15
    defaultQueryTimeoutSec: 30
    readonly: true
